### ISSUE TITLE
Error Interpreter Wrapper 

### ISSUE THREAD

**Issue by Gabzaya** [TannerGilbert/Tensorflow-2-Object-Counting#12]
Hello, I hope it's not to late to ask you about something. I am an absolute beginner and I try to follow your great tutorial. 
Everything went well running the code on tensorflow but when I tried to use tensorflow lite version these error appears : 
`ImportError: generic_type: type "InterpreterWrapper" is already registered!`

 I am working with tensorflow 2.5.1  and I didn't find any solution on web, sorry to disturb you maybe you experiment this? 
Maybe it's about dependencies for tflite? 

Thank you for your time

**Comment by Kennethvalerio212** [comment]
Does anyone solved this issue?

**Comment by JackDanHollister** [comment]
I also got this error with tflite! any help or advise would be great!

**Comment by Gabzaya** [comment]
Hey, I finally got rid of this error. It was about library installed on my environnement that weren't compatible. 

I work on anaconda, and if you check on the packages installed in the environnement you work on : you can notice that there is 2 Interpreter Wrapper on different site packages. I think that is what leads to the issue. 

I just created a fresh new environnement, and installed meticulously everything (like in this tutoriel) 

It works well now
