### ISSUE TITLE
Video, model and label map

### ISSUE THREAD

**Issue by konradkostrzewa** [TannerGilbert/Tensorflow-2-Object-Counting#6]
Could you please provide a link to the video, model and label map that you used to generate examples? I would like to reproduce your results

**Comment by TannerGilbert** [comment]
Model: http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz
Labelmap: https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt
Video: https://github.com/ahmetozlu/tensorflow_object_counting_api/raw/master/input_images_and_videos/pedestrian_survaillance.mp4
