### ISSUE TITLE
custom model created based on your tutorial doesn't work files

### ISSUE THREAD

**Issue by T-nesh** [TannerGilbert/Tensorflow-2-Object-Counting#8]
I am an absolute beginner,  follow your tutorial (https://www.youtube.com/watch?v=cvyDYdI2nEI&ab_channel=GilbertTanner) and successfully create a custom model but when trying the model with this TensorFlow-2-Object-Counting its doesn't work. 
can please help on how to link your object detection tutorial to the abject counting tutorial.

**Comment by TannerGilbert** [comment]
What do you mean with it doesn't work? What error are you getting?
